/**
 * GITHUB PUBLISHER
 * Creates a real GitHub repo for any artifact with one API call.
 * Wires in Vercel deployment link if configured.
 */

import dotenv from 'dotenv';
dotenv.config();

const GH_TOKEN    = process.env.GITHUB_TOKEN ?? '';
const GH_USERNAME = process.env.GITHUB_USERNAME ?? 'justappgrabbin';
const GH_API      = 'https://api.github.com';

export interface PublishResult {
  success:    boolean;
  repo_url?:  string;
  clone_url?: string;
  repo_name?: string;
  error?:     string;
}

function ghHeaders() {
  return {
    'Authorization': `Bearer ${GH_TOKEN}`,
    'Accept':        'application/vnd.github+json',
    'Content-Type':  'application/json',
    'X-GitHub-Api-Version': '2022-11-28',
  };
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80) || 'paper-worlds-app';
}

export async function createRepo(artifact: any): Promise<PublishResult> {
  if (!GH_TOKEN) return { success: false, error: 'No GitHub token configured' };

  const repoName = `pw-${slugify(artifact.name)}-${Date.now().toString(36)}`;
  const description = `Paper Worlds artifact · Gate ${artifact.gate}·${artifact.line} · ${artifact.dimension} · Address: ${artifact.address_22t}`;

  // 1. Create repo
  const createRes = await fetch(`${GH_API}/user/repos`, {
    method: 'POST',
    headers: ghHeaders(),
    body: JSON.stringify({
      name: repoName,
      description,
      private: false,
      auto_init: false,
      has_issues: false,
      has_wiki: false,
    }),
  });

  if (!createRes.ok) {
    const err = await createRes.json() as any;
    return { success: false, error: err.message ?? 'Failed to create repo' };
  }

  const repo = await createRes.json() as any;

  // 2. Commit files
  const files = buildFileTree(artifact);

  for (const [filePath, content] of Object.entries(files)) {
    const encoded = Buffer.from(content as string, 'utf8').toString('base64');
    await fetch(`${GH_API}/repos/${GH_USERNAME}/${repoName}/contents/${filePath}`, {
      method: 'PUT',
      headers: ghHeaders(),
      body: JSON.stringify({
        message: `✦ Initial commit · Paper Worlds · ${artifact.name}`,
        content: encoded,
      }),
    });
  }

  return {
    success:    true,
    repo_url:   repo.html_url,
    clone_url:  repo.clone_url,
    repo_name:  repoName,
  };
}

function buildFileTree(artifact: any): Record<string, string> {
  const html   = artifact.html || artifact.content || '';
  const name   = artifact.name;
  const gate   = artifact.gate;
  const addr   = artifact.signature;
  const addr22 = artifact.address_22t;

  const readme = `# ${name}

A Paper Worlds artifact · Built with consciousness coordinates.

## Ontological Address

\`\`\`
${addr}
\`\`\`

| Field | Value |
|-------|-------|
| Gate | ${gate} |
| Line | ${artifact.line} |
| Color | ${artifact.color} |
| Tone | ${artifact.tone} |
| Base | ${artifact.base} |
| Dimension | ${artifact.dimension} |
| Zodiac | ${artifact.zodiac} |
| House | ${artifact.house} |
| Planet | ${artifact.planet} |
| 22T Address | ${addr22?.toLocaleString()} |

## Run

Open \`index.html\` directly in any browser. No build step needed.

## Part of

- [YOU-N-I-VERSE](https://github.com/${GH_USERNAME}) consciousness ecosystem
- [Synthia Server](https://synthia-server.onrender.com)
- Paper Worlds mesh network

---
*Generated by Paper Worlds · ${new Date().toISOString()}*
`;

  const manifest = JSON.stringify({
    name,
    version: '1.0.0',
    description: `Paper Worlds artifact · Gate ${gate}`,
    ontological_address: {
      signature: addr,
      address_22t: addr22,
      gate: artifact.gate,
      line: artifact.line,
      color: artifact.color,
      tone: artifact.tone,
      base: artifact.base,
      dimension: artifact.dimension,
      zodiac: artifact.zodiac,
      house: artifact.house,
      planet: artifact.planet,
    },
    source: artifact.source,
    created_at: artifact.created_at,
    paper_worlds: {
      supabase_url: process.env.SUPABASE_URL,
      synthia_url:  process.env.SYNTHIA_URL,
    }
  }, null, 2);

  const gitignore = `node_modules/\n.env\n.env.local\n*.log\n.DS_Store\n`;

  return {
    'index.html':           html,
    'README.md':            readme,
    'manifest.json':        manifest,
    '.gitignore':           gitignore,
  };
}

// List repos created by Paper Worlds
export async function listPaperWorldsRepos(): Promise<any[]> {
  if (!GH_TOKEN) return [];
  const res = await fetch(`${GH_API}/user/repos?per_page=100&sort=created`, {
    headers: ghHeaders()
  });
  if (!res.ok) return [];
  const repos = await res.json() as any[];
  return repos.filter((r: any) => r.name.startsWith('pw-'));
}
